<dec f='ffmpeg/libavcodec/dirac_dwt.h' l='71' type='DWTCompose [8]'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='343' u='r' c='spatial_compose_dd97i_dy_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='367' u='r' c='spatial_compose_dirac53i_dy_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='389' u='r' c='spatial_compose_dd137i_dy_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='413' u='m' c='spatial_compose_haari_dy_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='421' u='m' c='spatial_compose_haari_dy_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='448' u='m' c='spatial_compose_fidelity_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='457' u='r' c='spatial_compose_daub97i_dy_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='531' u='r' c='ff_spatial_idwt_init_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='534' u='r' c='ff_spatial_idwt_init_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='537' u='r' c='ff_spatial_idwt_init_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='541' u='m' c='ff_spatial_idwt_init_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='544' u='r' c='ff_spatial_idwt_init_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='547' u='m' c='ff_spatial_idwt_init_8bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='343' u='r' c='spatial_compose_dd97i_dy_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='367' u='r' c='spatial_compose_dirac53i_dy_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='389' u='r' c='spatial_compose_dd137i_dy_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='413' u='m' c='spatial_compose_haari_dy_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='421' u='m' c='spatial_compose_haari_dy_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='448' u='m' c='spatial_compose_fidelity_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='457' u='r' c='spatial_compose_daub97i_dy_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='531' u='r' c='ff_spatial_idwt_init_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='534' u='r' c='ff_spatial_idwt_init_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='537' u='r' c='ff_spatial_idwt_init_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='541' u='m' c='ff_spatial_idwt_init_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='544' u='r' c='ff_spatial_idwt_init_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='547' u='m' c='ff_spatial_idwt_init_10bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='343' u='r' c='spatial_compose_dd97i_dy_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='367' u='r' c='spatial_compose_dirac53i_dy_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='389' u='r' c='spatial_compose_dd137i_dy_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='413' u='m' c='spatial_compose_haari_dy_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='421' u='m' c='spatial_compose_haari_dy_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='448' u='m' c='spatial_compose_fidelity_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='457' u='r' c='spatial_compose_daub97i_dy_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='531' u='r' c='ff_spatial_idwt_init_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='534' u='r' c='ff_spatial_idwt_init_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='537' u='r' c='ff_spatial_idwt_init_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='541' u='m' c='ff_spatial_idwt_init_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='544' u='r' c='ff_spatial_idwt_init_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt_template.c' l='547' u='m' c='ff_spatial_idwt_init_12bit'/>
<use f='ffmpeg/libavcodec/dirac_dwt.c' l='76' u='m' c='ff_spatial_idwt_slice2'/>
<offset>768</offset>
